server:
  port: 8081
spring:
  application:
    name: user-server
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:7434/user_db
    username: kimgech
    password: 123
#  main:
#    allow-bean-definition-overriding: true
  config:
    import: optional:configserver:http://localhost:8888


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

    instanceId: ${eureka.instance.hostname}:${spring.application.name}
    statusPageUrl: http://${eureka.hostname}/
    healthCheckUrl: http://${eureka.hostname}/actuator/health
    secureHealthCheckUrl: http://${eureka.hostname}/actuator/health

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html