spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: registry-server
    # Simply telling Eureka server to NOT fetch or register to any server since it's not a client.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761